# Generated by Django 3.0 on 2020-12-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panner_Has_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Add at')),
                ('panner_articles', models.ManyToManyField(to='commands.Panner_Articles')),
            ],
        ),
        migrations.AlterField(
            model_name='panner',
            name='panner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.Panner_Has_Articles'),
        ),
    ]
