# Generated by Django 3.1.4 on 2020-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panner',
            name='articles',
        ),
        migrations.AddField(
            model_name='panner',
            name='articles',
            field=models.ManyToManyField(related_name='Articles', to='articles.Articles'),
        ),
    ]
