# Generated by Django 3.0 on 2020-12-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('commands', '0002_auto_20201210_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles')),
            ],
        ),
        migrations.RemoveField(
            model_name='panner_articles',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='panner_articles',
            name='quantity',
        ),
        migrations.AddField(
            model_name='panner_articles',
            name='date_add',
            field=models.DateTimeField(auto_now=True, verbose_name='Add at'),
        ),
        migrations.AlterField(
            model_name='panner',
            name='panner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.Panner_Articles'),
        ),
        migrations.DeleteModel(
            name='Panner_Has_Articles',
        ),
        migrations.AddField(
            model_name='panner_articles',
            name='panner_articles',
            field=models.ManyToManyField(to='commands.Container'),
        ),
    ]
