# Generated by Django 3.1.4 on 2020-12-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('commands', '0002_auto_20201202_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panner',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Articles_On_Panner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='Quantity')),
                ('user_cookies', models.CharField(max_length=255, unique=True, verbose_name='User cookies')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
            ],
        ),
        migrations.AlterField(
            model_name='panner',
            name='articles',
            field=models.ManyToManyField(related_name='Articles', to='commands.Articles_On_Panner'),
        ),
    ]
