# Generated by Django 3.0 on 2020-12-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Alimentation', 'ALIMENTATION'), ('Mode', 'MODE'), ('Informatic', 'INFORMATIC'), ('Sports-Health', 'SPORTS & HEALTH')], max_length=40, unique=True, verbose_name='Category article')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(default='N/A', verbose_name='Description')),
                ('cover', models.ImageField(upload_to='articles/')),
                ('devise', models.CharField(choices=[('FCFA', 'XOF'), ('EUR', 'EUR'), ('DOL', 'DOL')], default='XOF', max_length=10, verbose_name='Devise')),
                ('available', models.BooleanField(default=True, verbose_name='is Available')),
                ('star', models.BooleanField(default=False, verbose_name='is Star ?')),
                ('promo', models.BooleanField(default=False, verbose_name='is in Promo ?')),
                ('promo_price', models.IntegerField(default=0, verbose_name='Promo price')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('category', models.ManyToManyField(related_name='Category', to='articles.Category')),
                ('images', models.ManyToManyField(blank=True, related_name='Images', to='articles.Images')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Administrator')),
            ],
        ),
    ]
