# Generated by Django 3.1.3 on 2020-12-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Trader', 'TRADER'), ('Business Man', 'BUSINESS MAN')], max_length=15, unique=True, verbose_name='Admin Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Telephone')),
                ('activity_name', models.CharField(max_length=40, unique=True, verbose_name='Activity Name')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name='Last name')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='First name')),
                ('date_birth', models.DateField(verbose_name='Birth date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.category')),
            ],
        ),
    ]
